import { Link } from 'react-router-dom'
import { products, categories, formatPrice } from '../data/products'

export default function Home() {
  return <>
    <section className="hero section"><div className="hero-copy"><span className="eyebrow">YOUR TRUSTED TECH STORE</span><h1>Technology that <em>works</em> for you.</h1><p>Shop quality laptops, computers, accessories and office technology built around value, reliability and great service.</p><div className="hero-actions"><Link className="primary-button" to="/shop">Shop products →</Link><Link className="secondary-button" to="/about">Why Soft-Gate</Link></div><div className="trust-row"><span><b>Quality</b> Carefully selected tech</span><span><b>Reliable</b> Products you can count on</span><span><b>Support</b> Here when you need us</span></div></div><div className="hero-art"><div className="hero-device">S</div><div className="floating-card">NEW<br/><strong>Premium Laptops</strong></div></div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">SHOP BY CATEGORY</span><h2>Everything you need.</h2></div><p>From everyday computing to complete office setups.</p></div><div className="category-grid">{categories.slice(1,7).map((category)=><Link className="category-card" key={category} to={`/shop?category=${encodeURIComponent(category)}`}><span className="category-icon">▣</span><h3>{category}</h3><p>Explore products</p><span>↗</span></Link>)}</div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">FEATURED PRODUCTS</span><h2>Built for your next move.</h2></div><Link className="text-link" to="/shop">View all →</Link></div><div className="product-grid">{products.slice(0,6).map(p=><Link className="product-card" to={`/product/${p.id}`} key={p.id}><div className="product-image">▱</div><span className="tag">{p.badge}</span><h3>{p.name}</h3><p>{p.description}</p><strong>{formatPrice(p.price)}</strong></Link>)}</div></section>
    <section className="why section"><span className="eyebrow">WHY SOFT-GATE</span><h2>A better way to shop for tech.</h2><div className="why-grid"><div><b>01</b><h3>Quality first</h3><p>Dependable products selected for real value.</p></div><div><b>02</b><h3>Helpful service</h3><p>Straightforward guidance before and after purchase.</p></div><div><b>03</b><h3>Ready for business</h3><p>Equip your home, school or office with confidence.</p></div></div></section>
  </>
}
