import { Link } from 'react-router-dom'
import { products, categories, formatPrice } from '../data/products'
import ProductCard from '../components/ProductCard'

const categoryMeta = { Laptops: 'Business & personal', Desktops: 'Powerful workstations', Monitors: 'Clear, crisp displays', Accessories: 'Complete your setup', 'Office Tech': 'Work smarter', Storage: 'Keep it all safe' }

export default function Home() {
  return <main>
    <section className="hero-home"><div className="hero-copy"><span className="eyebrow">SOFT-GATE ENTERPRISES COMPUTER</span><h1>Power your work. <em>Upgrade your world.</em></h1><p>Shop dependable laptops, computers and accessories at prices built for students, professionals, homes and businesses.</p><div className="hero-actions"><Link className="primary-button" to="/shop">Shop now →</Link><Link className="secondary-button" to="/shop?category=Laptops">Explore laptops</Link></div><div className="trust-row"><span>✓ <b>Quality products</b></span><span>✓ <b>Fast delivery</b></span><span>✓ <b>Helpful support</b></span></div></div><div className="hero-visual"><div className="hero-sale"><small>WEEKLY DEALS</small><b>Up to</b><strong>15% OFF</strong><span>selected technology</span></div><img src={products[0].image} alt="Premium laptop"/><div className="hero-floating">★ 4.8 rated<br/><b>Top customer choice</b></div></div></section>
    <section className="benefits"><div>🚚 <span><b>Nationwide delivery</b><small>We deliver to you</small></span></div><div>✓ <span><b>Quality guaranteed</b><small>Products selected with care</small></span></div><div>↻ <span><b>Customer support</b><small>We're here to help</small></span></div><div>🔒 <span><b>Secure shopping</b><small>Safe checkout experience</small></span></div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">SHOP BY CATEGORY</span><h2>Find what you need.</h2></div><Link to="/shop" className="text-link">View all categories →</Link></div><div className="category-grid">{categories.slice(1).map(category => <Link className="category-card" key={category} to={`/shop?category=${encodeURIComponent(category)}`}><span className="category-icon">{category === 'Laptops' ? '▱' : category === 'Accessories' ? '⌨' : category === 'Monitors' ? '▥' : category === 'Storage' ? '▤' : '▣'}</span><div><h3>{category}</h3><p>{categoryMeta[category] || 'Explore products'}</p></div><span className="category-arrow">→</span></Link>)}</div></section>
    <section className="section deals-section"><div className="section-heading"><div><span className="eyebrow">DEALS OF THE WEEK</span><h2>Great tech. Better value.</h2></div><Link to="/shop" className="text-link">Shop all deals →</Link></div><div className="product-grid">{products.slice(0, 6).map(product => <ProductCard key={product.id} product={product}/>)}</div></section>
    <section className="promo-banner"><div><span className="eyebrow">BUILD YOUR SETUP</span><h2>Everything your workspace needs.</h2><p>From a powerful laptop to the smallest essential accessory, build a setup that works for you.</p><Link to="/shop" className="primary-button">Start shopping →</Link></div><div className="promo-stats"><strong>12+</strong><span>Products ready to shop</span><strong>4.7/5</strong><span>Average customer rating</span></div></section>
    <section className="section testimonials"><div className="section-heading"><div><span className="eyebrow">CUSTOMER LOVE</span><h2>Shopping made easier.</h2></div></div><div className="testimonial-grid"><article><span>★★★★★</span><p>“The product information was clear and the buying process was straightforward. Exactly what I needed.”</p><b>Verified customer</b></article><article><span>★★★★★</span><p>“A professional experience from browsing to delivery. Soft-Gate is now my first stop for computer accessories.”</p><b>Verified customer</b></article><article><span>★★★★★</span><p>“Good value, helpful service and a clean shopping experience. I would recommend them.”</p><b>Verified customer</b></article></div></section>
  </main>
}
